data <- read.table("household_power_consumption.txt", header= TRUE, sep=";", stringsAsFactors = FALSE, dec=".")
twodays <- subset(data, Date %in% c("1/2/2007", "2/2/2007"))
datetime <- strptime(paste(twodays$Date, twodays$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(datetime, twodays$Sub_metering_1, col="black", type="l", ylab="Energy sub Metering", xlab=" ")
lines(datetime, twodays$Sub_metering_2, col="red", type="l")
lines(datetime, twodays$Sub_metering_3, col="blue", type="l")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1, lwd=2.5)
dev.off()
