data <- read.table("household_power_consumption.txt", header= TRUE, sep=";", stringsAsFactors = FALSE, dec=".")
twodays <- subset(data, Date %in% c("1/2/2007", "2/2/2007"))
datetime <- strptime(paste(twodays$Date, twodays$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
globalreactivepower <- as.numeric(twodays$Global_reactive_power)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(datetime, globalactivepower, type="l", ylab="Global Active Power", xlab=" ")
plot(datetime, twodays$Voltage, type="l", ylab="Voltage")
plot(datetime, twodays$Sub_metering_1, col="black", type="l", ylab="Energy sub Metering", xlab=" ")
lines(datetime, twodays$Sub_metering_2, col="red", type="l")
lines(datetime, twodays$Sub_metering_3, col="blue", type="l")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1, lwd=2.5, bty="n")
plot(datetime, globalreactivepower, type="l", ylab="Global_reactive_power")
dev.off()